version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '5173:5173' # Adjust to your React port
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: ./server
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
    volumes:
      - ./server:/app
      - /app/node_modules

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
